---
- name: system setup for workstation
  hosts: localhost
  connection: local
  become: true
  vars:
    target_user: "{{ lookup('env', 'USER') }}"
    ansible_python_interpreter: /usr/bin/python3
    rustdesk_version: "1.2.3"
    ubuntu_codename: "{{ ansible_distribution_release }}"
    dots_path: "/home/{{ target_user }}/Hyprland-Dots"
    installer_path: "/tmp/hyprland-installer"

  tasks:
    - name: setup current user
      import_tasks: ../../common_tasks/user_setup.yml
    - name: install docker
      import_tasks: ../../common_tasks/docker.yml

    - name: setup isaac sim and lab
      import_tasks: tasks/isaac.yml

    - name: configure passwordless sudo
      import_tasks: ../../common_tasks/sudo_nopasswd.yml

  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted
