---
- name: system setup for workstation
  hosts: localhost
  connection: local
  become: true
  vars:
    target_user: "arika"
    rustdesk_version: "1.2.3"
    ubuntu_codename: "noble"
    dots_path: "/home/arika/Hyprland-Dots"
    installer_path: "/tmp/hyprland-installer"

  tasks:
    - name: setup dots symlinks
      import_tasks: tasks/dots.yml
    - name: force transparent waybar
      import_tasks: tasks/hyprland_waybar_transparent.yml
    - name: setup ros 2 jazzy environment
      import_tasks: tasks/ros2.yml

    - name: hyprland install assume nvida gpu
      import_tasks: tasks/hyprland.yml

    - name: development tools
      import_tasks: tasks/dev_tools.yml

    - name: desktop applications and base system
      import_tasks: tasks/apps.yml

    - name: shell configuration and aliases
      import_tasks: tasks/shell_config.yml
