---
- name: download ros 2 gpg key
  get_url:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    dest: /usr/share/keyrings/ros-archive-keyring.gpg

- name: add ros 2 repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu {{ ansible_lsb.codename }} main"
    filename: ros2
    state: present

- name: install ros 2 jazzy
  apt:
    name: ros-jazzy-desktop
    state: present

- name: ensure .zshrc sources .ros2_settings from repo
  ansible.builtin.shell:
    cmd: |
      sudo -u {{ target_user }} touch /home/{{ target_user }}/.zshrc
      sudo -u {{ target_user }} grep -qF 'source {{ playbook_dir }}/configs/ros2_settings.zsh' /home/{{ target_user }}/.zshrc || \
      echo 'source {{ playbook_dir }}/configs/ros2_settings.zsh' | sudo -u {{ target_user }} tee -a /home/{{ target_user }}/.zshrc
