---
- name: ensure .config directory exists
  become_user: "{{ target_user }}"
  file:
    path: "/home/{{ target_user }}/.config"
    state: directory

- name: check existing config paths
  become_user: "{{ target_user }}"
  stat:
    path: "/home/{{ target_user }}/.config/{{ item }}"
  register: config_stats
  loop:
    - hypr
    - kitty
    - waybar
    - swaync
    - rofi
    - wallust
    - ags
    - fastfetch
    - btop
    - cava
    - wlogout

- name: remove existing config directories if they are not symlinks
  become_user: "{{ target_user }}"
  file:
    path: "{{ item.stat.path }}"
    state: absent
  when: item.stat.exists and not item.stat.islnk
  loop: "{{ config_stats.results }}"

- name: symlink dots config directories
  become_user: "{{ target_user }}"
  file:
    src: "{{ dots_path }}/config/{{ item }}"
    dest: "/home/{{ target_user }}/.config/{{ item }}"
    state: link
    force: yes
  loop:
    - hypr
    - kitty
    - waybar
    - swaync
    - rofi
    - wallust
    - ags
    - fastfetch
    - btop
    - cava
    - wlogout

- name: ensure .zshrc sources hypr custom settings from repo
  become_user: "{{ target_user }}"
  lineinfile:
    path: "/home/{{ target_user }}/.zshrc"
    line: "source {{ playbook_dir }}/configs/hypr_custom.zsh"
    create: yes
    state: present

- name: set wallDIR in hyprland user env variables
  become_user: "{{ target_user }}"
  lineinfile:
    path: "/home/{{ target_user }}/.config/hypr/UserConfigs/ENVariables.conf"
    line: "env = wallDIR,/home/arika/Documents/ansible_playbooks/background"
    create: yes
    state: present
