---
- name: clone linuxbeginnings ubuntu hyprland repository
  become_user: "{{ target_user }}"
  git:
    repo: https://github.com/LinuxBeginnings/Ubuntu-Hyprland.git
    dest: "{{ installer_path }}"
    version: "24.04"
    depth: 1

- name: prepare preset file for automated installation
  become_user: "{{ target_user }}"
  shell: cp preset.sh my_preset.sh
  args:
    chdir: "{{ installer_path }}"
    creates: "{{ installer_path }}/my_preset.sh"
  # Ignore errors in check mode because the directory won't exist yet
  ignore_errors: "{{ ansible_check_mode }}"

- name: set nvidia support in preset
  become_user: "{{ target_user }}"
  lineinfile:
    path: "{{ installer_path }}/my_preset.sh"
    regexp: '^NVIDIA=' 
    line: 'NVIDIA="Y"'
  ignore_errors: "{{ ansible_check_mode }}"

- name: execute the hyprland installation
  become_user: "{{ target_user }}"
  shell: ./install.sh --preset my_preset.sh
  args:
    chdir: "{{ installer_path }}"
    creates: "/home/{{ target_user }}/.config/hypr/hyprland.conf"
  ignore_errors: "{{ ansible_check_mode }}"
