---
- name: clone linuxbeginnings ubuntu hyprland repository
  become_user: "{{ target_user }}"
  git:
    repo: https://github.com/LinuxBeginnings/Ubuntu-Hyprland.git
    dest: "{{ dots_path }}"
    version: "24.04"
    depth: 1

- name: check if hyprland repo exists
  stat:
    path: "{{ dots_path }}"
  register: hypr_repo

- name: prepare preset file for automated installation
  become_user: "{{ target_user }}"
  shell: cp preset.sh my_preset.sh
  args:
    chdir: "{{ dots_path }}"
    creates: "{{ dots_path }}/my_preset.sh"
  # Force this to run even in check mode so lineinfile doesn't fail
  check_mode: no

- name: set nvidia support in preset
  become_user: "{{ target_user }}"
  lineinfile:
    path: "{{ dots_path }}/my_preset.sh"
    regexp: '^NVIDIA=' 
    line: 'NVIDIA="Y"'
  # Force this to run even in check mode
  check_mode: no

- name: execute the hyprland installation
  become_user: "{{ target_user }}"
  shell: ./install.sh --preset my_preset.sh
  args:
    chdir: "{{ dots_path }}"
    creates: "/home/{{ target_user }}/.config/hypr/hyprland.conf"
  when: hypr_repo.stat.exists or not ansible_check_mode
