---
- name: create general shell settings file
  become_user: "{{ target_user }}"
  copy:
    dest: "/home/{{ target_user }}/.shell_settings"
    content: |
      # Quick config/reload
      alias settings="nano ~/.zshrc"
      alias reload="source ~/.zshrc"

      # tmux helpers
      alias tma="tmux attach -t"
      alias tmn="tmux new -t"
    mode: '0644'

- name: ensure .zshrc sources .shell_settings
  become_user: "{{ target_user }}"
  lineinfile:
    path: "/home/{{ target_user }}/.zshrc"
    line: "source ~/.shell_settings"
    create: yes
    state: present
