---
- name: download ros 2 gpg key
  get_url:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    dest: /usr/share/keyrings/ros-archive-keyring.gpg

- name: add ros 2 repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu {{ ubuntu_codename }} main"
    filename: ros2
    state: present

- name: install ros 2 jazzy
  apt:
    name: ros-jazzy-desktop
    state: present

- name: Create ansible_configs directory in user home
  file:
    path: "/home/{{ target_user }}/.ansible_configs"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'

- name: Copy ros2_settings.zsh to user home
  copy:
    src: "{{ playbook_dir }}/configs/ros2_settings.zsh"
    dest: "/home/{{ target_user }}/.ansible_configs/ros2_settings.zsh"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0644'

- name: ensure .zshrc sources .ros2_settings from local copy
  ansible.builtin.shell:
    cmd: |
      sudo -u {{ target_user }} touch /home/{{ target_user }}/.zshrc
      sudo -u {{ target_user }} grep -qF 'source $HOME/.ansible_configs/ros2_settings.zsh' /home/{{ target_user }}/.zshrc || \
      echo 'source $HOME/.ansible_configs/ros2_settings.zsh' | sudo -u {{ target_user }} tee -a /home/{{ target_user }}/.zshrc
