---
- name: ensure .zshrc sources general shell settings from repo
  become_user: "{{ target_user }}"
  lineinfile:
    path: "/home/{{ target_user }}/.zshrc"
    line: "source {{ playbook_dir }}/configs/shell_settings.zsh"
    create: yes
    state: present
