---
- name: system setup for server
  hosts: localhost
  connection: local
  become: true
  vars:
    target_user: "arika"

  tasks:
    - name: setup ros 2 jazzy environment
      import_tasks: tasks/ros2.yml

    - name: development tools
      import_tasks: tasks/dev_tools.yml

    - name: headless applications
      import_tasks: tasks/headless_apps.yml
    - name: install docker
      import_tasks: ../common_tasks/docker.yml
    - name: install bun
      import_tasks: ../common_tasks/bun.yml
    - name: configure unattended upgrades
      import_tasks: ../common_tasks/unattended_upgrades.yml
    - name: install nmtui
      import_tasks: ../common_tasks/nmtui.yml
    - name: install tmux
      import_tasks: ../common_tasks/tmux.yml
