---
- name: Clone VERT repository
  become_user: "{{ target_user }}"
  git:
    repo: https://github.com/VERT-sh/VERT
    dest: "/home/{{ target_user }}/VERT"
    version: main
    depth: 1

- name: Build VERT docker image from source
  become_user: "{{ target_user }}"
  ansible.builtin.shell:
    cmd: |
      docker build -t vert-sh/vert \
          --build-arg PUB_ENV=production \
          --build-arg PUB_HOSTNAME=vert.sh \
          --build-arg PUB_PLAUSIBLE_URL=https://plausible.example.com \
          --build-arg PUB_VERTD_URL=https://vertd.vert.sh \
          --build-arg PUB_DONATION_URL=https://donations.vert.sh \
          --build-arg PUB_DISABLE_ALL_EXTERNAL_REQUESTS=false \
          --build-arg PUB_STRIPE_KEY="" .
    chdir: "/home/{{ target_user }}/VERT"
